"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const csv = fs.readFileSync(path.join(root, "csv-import.js"), "utf8");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const serviceWorker = fs.readFileSync(path.join(root, "service-worker.js"), "utf8");
const schema = fs.readFileSync(path.join(root, "supabase-schema.sql"), "utf8");

assert.doesNotMatch(csv, /\bfetch\s*\(|XMLHttpRequest|sendBeacon|WebSocket/u, "CSV module must not contain a network path");
assert.match(app, /localAi\.generateCards\(redactedText/u, "AI must receive only redacted TXT");
assert.doesNotMatch(app, /generateCards\([^\n]*(?:aiCsvCards|safeText)/u, "CSV data must not be passed to AI");
assert.match(app, /localCsv\.looksLikeCsv\(decoded\.text\)/u, "CSV-shaped content must use the local parser even with a TXT extension");
assert.match(app, /source && localCsv\.looksLikeCsv\(source\)/u, "pasted CSV must use the local parser before any AI call");
assert.match(app, /fileReadRequestId !== state\.aiFileReadRequestId/u, "stale file reads must be ignored");
assert.match(app, /state\.aiFileReadRequestId \+= 1/u, "clearing an import must cancel pending file reads");
assert.match(app, /els\.aiMemoInput\.readOnly = busy/u, "the memo must not be edited while a file read can overwrite it");
assert.match(app, /const manualText = preserveManualMemoText\(previousMemo, previousLoadedText\)/u, "file reselection must separate prior file TXT from manual edits");
assert.match(app, /\[selectedText, manualText\]\.filter\(Boolean\)\.join/u, "new TXT files must not overwrite separately entered manual text");
assert.match(app, /state\.aiFileReadPending \|\| state\.aiGeneratePending/u, "old result cards must be blocked while import work is pending");
assert.match(app, /previousUserId !== nextUserId\)[\s\S]*clearUserScopedUiState\(/u, "changing authenticated users must clear private import state");
assert.match(app, /function clearUserScopedUiState\([^)]*\)[\s\S]*clearAiImportData\(\)/u, "user state cleanup must cancel AI and file requests");
assert.match(app, /function clearUserScopedUiState\([^)]*\)[\s\S]*clearFaqUserScopedUiState\(\)/u, "changing users must cancel FAQ requests and clear their conversation");
assert.match(app, /function clearUserScopedUiState\([^)]*\)[\s\S]*state\.entries = \[\][\s\S]*state\.templates = \[\]/u, "changing users must immediately clear the previous user's cards and templates");
assert.match(app, /function clearUserScopedUiState\([^)]*\)[\s\S]*els\.authForm\.reset\(\)[\s\S]*resetTemplateForm\(\)/u, "changing users must clear credentials and unfinished template text");
assert.match(app, /async function loadCloudData\(\)[\s\S]*captureUserScope\(\)[\s\S]*isCurrentUserScope\(scope\)/u, "stale cloud loads must not cross user boundaries");
assert.match(app, /async function (?:create|update)CloudEntry[\s\S]*isCurrentUserScope\(scope\)/u, "stale cloud saves must not update the next user's UI");
assert.match(app, /async function handleImportBackup[\s\S]*const importScope = [^;]*captureUserScope\(\)[\s\S]*isCurrentUserScope\(scope\)/u, "backup restoration must stop if the authenticated user changes");
assert.match(app, /officialUrl: normalizeExternalUrl\(source\.officialUrl\)/u, "saved official links must reject non-HTTP protocols");
assert.match(app, /mypageUrl: normalizeExternalUrl\(source\.mypageUrl\)/u, "saved mypage links must reject non-HTTP protocols");
assert.match(app, /function companyLogoSources[\s\S]*normalizeExternalImageUrl\(entry\.logoUrl\)/u, "automatic image requests must use the stricter public HTTPS policy");
assert.match(app, /function consolidateAiImportCards[\s\S]*logoUrl: ""/u, "AI and CSV candidates must not create automatic image requests");
assert.match(app, /async function handleImportBackup[\s\S]*logoUrl: ""/u, "backup image URLs must not create automatic requests");
assert.doesNotMatch(app, /logo\.clearbit\.com|google\.com\/s2\/favicons|apple-touch-icon|\/favicon\.(?:svg|ico)/u, "company cards must not automatically disclose application targets to logo services or company origins");
assert.doesNotMatch(app, /onAuthStateChange\(async/u, "Supabase auth callbacks must not await client API calls inside the callback");
assert.match(html, /@supabase\/supabase-js@2\.110\.8\/dist\/umd\/supabase\.min\.js/u, "the authentication SDK must be pinned to a tested full version");
assert.doesNotMatch(app, /data-(?:detail|edit|delete|template-(?:copy|edit|delete))-id="\$\{(?:entry|template)\.id\}"/u, "record ids must be escaped before entering HTML attributes");
assert.match(app, /id: normalizeImportedRecordId\((?:entry|template)(?:\?\.|\.)id\)/u, "untrusted backup record ids must be validated or regenerated");
assert.match(app, /function isValidBackup[\s\S]*value\.version >= 1[\s\S]*value\.entries\.every\(isValidBackupEntryRecord\)/u, "backup version and record field types must be validated");
assert.match(app, /function prepareBackupEntryRestore[\s\S]*mergeBackupEntries/u, "backup cards must consolidate by card identity before saving");
assert.match(app, /entryRestorePlan\.blockingIssues\.length[\s\S]*復元を中止しました/u, "backup text that cannot be merged must fail visibly before saving");
assert.match(app, /mergeImportedEntry\([^;]*\{ textLimit: 100_000 \}\)/u, "backup notes must use the stored-data length limit");
assert.match(app, /!Number\.isFinite\(nextEntry\.sortOrder\)[\s\S]*incoming\.sortOrder/u, "backup order must fill an unset existing order");
assert.match(app, /includeSortOrder: !entrySortProbe\.error/u, "cloud backup restoration must preserve entry ordering when the column exists");
assert.match(app, /includeSortOrder: !templateSortProbe\.error/u, "cloud backup restoration must preserve template ordering when the column exists");
assert.match(app, /state\.aiReviewedConflictKeys\.add\(importReviewKey\)/u, "reviewed import conflicts must not loop forever");
assert.match(app, /sensitiveFields\.has\(detail\.field\)[\s\S]*値は確認画面の中だけで表示します/u, "sensitive conflict values must stay out of the result list");
assert.match(app, /data-import-conflict-index/u, "the confirmation screen must offer an explicit imported-value action");
assert.doesNotMatch(app, /data-import-conflict-[^=]*="\$\{[^}]*(?:incomingValue|existingValue)/u, "conflict values must not be embedded in data attributes");
assert.match(html, /id="aiMemoFileInput"[^>]*multiple/u);
assert.match(html, /accept="[^"]*\.csv/u);
assert.match(html, /伏せ字は完全ではありません。パスワード・合言葉・秘密情報は入力しないでください/u);
assert.ok(html.indexOf("./csv-import.js") < html.indexOf("./app.js"), "CSV parser must load before app.js");
assert.match(serviceWorker, /"\.\/csv-import\.js"/u);
assert.match(schema, /create unique index entries_user_company_track_unique_idx/iu, "cloud storage must reject simultaneous duplicate cards");
assert.match(schema, /normalize\(company_name, NFKC\)/iu, "cloud duplicate identity must use the same Unicode normalization family as the client");
assert.match(schema, /group by[\s\S]*user_id[\s\S]*company_name[\s\S]*track_type[\s\S]*having count\(\*\) > 1/iu, "existing duplicates must be detected without deletion before adding the constraint");
assert.match(app, /error\?\.code === "23505"[\s\S]*entries_user_company_track_unique_idx/iu, "only the card identity constraint should receive the duplicate-card message");
assert.match(app, /closeAiImportDialog\(false\);\s*\n\s*openEntryDialog/u, "reviewing one card must retain the remaining import plan");

console.log("CSV import security wiring tests passed");
